-- Execute conectado ao database api_fundamentos.
-- Estrutura didatica: categorias 1:N produtos.

-- 1. Criar categorias.
CREATE TABLE IF NOT EXISTS public.categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL UNIQUE,
    descricao VARCHAR(255)
);

-- 2. Criar produtos.
CREATE TABLE IF NOT EXISTS public.produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    preco NUMERIC(12, 2) NOT NULL CHECK (preco >= 0),
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

-- 3. Adicionar a coluna que representa o lado N do relacionamento.
ALTER TABLE public.produtos
    ADD COLUMN IF NOT EXISTS categoria_id BIGINT;

-- 4. Criar a chave estrangeira: uma categoria possui varios produtos.
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_produtos_categorias'
          AND conrelid = 'public.produtos'::regclass
    ) THEN
        ALTER TABLE public.produtos
            ADD CONSTRAINT fk_produtos_categorias
            FOREIGN KEY (categoria_id)
            REFERENCES public.categorias (id)
            ON UPDATE CASCADE
            ON DELETE SET NULL;
    END IF;
END;
$$;

-- 5. Criar indice para consultas por categoria.
CREATE INDEX IF NOT EXISTS idx_produtos_categoria_id
    ON public.produtos (categoria_id);

-- 6. Conferir tabelas, colunas e relacionamento criados.
SELECT
    table_name,
    column_name,
    data_type
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name IN ('categorias', 'produtos')
ORDER BY table_name, ordinal_position;

SELECT
    con.conname AS constraint_name,
    pg_get_constraintdef(con.oid) AS definicao
FROM pg_constraint con
WHERE con.conrelid = 'public.produtos'::regclass
  AND con.contype = 'f';
